class AssetLoader {
  var assets = {
    'sbte' : 'assets/sbte.png',
    'spotify': 'assets/spotify.png',
    'hbo max': 'assets/hbo max.png',
    'wetransfer': 'assets/wetransfer.ai',
    'twitch': 'assets/twitch.png',
    'disney+': 'assets/disney+.png',
    'hulu': 'assets/hulu.png',
    'disney': 'assets/disney.ai',
    'paramount': 'assets/paramount.png',
    'youtube': 'assets/youtube.png',
    'discovery+': 'assets/discovery+.png',
    'hbo': 'assets/hbo.ai',
    'plex': 'assets/plex.svg',
    'amazon prime video': 'assets/amazon prime video.png',
    'soundcloud': 'assets/soundcloud.png',
    'pluto tv': 'assets/pluto tv.png',
    'netflix': 'assets/netflix.png',
    'tubi': 'assets/tubi.png',
    'pandora': 'assets/pandora.png',
    'coinbase': 'assets/coinbase.png',
    'venmo': 'assets/venmo.png',
    'newegg': 'assets/newegg.png',
    'aliexpress': 'assets/aliexpress.png',
    'walmart': 'assets/walmart.png',
    'paypal': 'assets/paypal.png',
    'amazon': 'assets/amazon.png',
    'ebay': 'assets/ebay.png',
    'trello': 'assets/trello.png',
    'figma': 'assets/figma.png',
    'evernote': 'assets/evernote.png',
    'microsoft outlook': 'assets/microsoft outlook.png',
    'jira': 'assets/jira.png',
    'note' : 'assets/paper.png',
    'github': 'assets/github.png',
    'bitgo': 'assets/bitgo.png',
    'gitlab': 'assets/gitlab.png',
    'bitbucket': 'assets/bitbucket.png',
    'jenkins': 'assets/jenkins.png',
    'asana': 'assets/asana.png',
    'hootsuite': 'assets/hootsuite.png',
    'sketch': 'assets/sketch.png',
    'vk': 'assets/vk.png',
    'snapchat': 'assets/snapchat.png',
    'tiktok': 'assets/tiktok.png',
    'discord': 'assets/discord.png',
    'linkedin': 'assets/linkedin.png',
    'twitter': 'assets/twitter.png',
    'slack': 'assets/slack.png',
    'telegram': 'assets/telegram.png',
    'skype': 'assets/skype.png',
    'twitter x': 'assets/twitter x.png',
    'instagram': 'assets/instagram.png',
    'facebook': 'assets/facebook.png',
    'whatsapp': 'assets/whatsapp.png',
    'reddit': 'assets/reddit.png',
    'zoom': 'assets/zoom.png',
    'pluto': 'assets/pluto.svg',
    'quora': 'assets/quora.png',
    'postman': 'assets/postman.png',
    'docker': 'assets/docker.png',
    'canva': 'assets/canva.png',
    'raspberry pi': 'assets/raspberry pi.png',
    'pinterest': 'assets/pinterest.png',
    'mysql': 'assets/mysql.png',
    'adobe': 'assets/adobe.ai',
    'cloudflare': 'assets/cloudflare.png',
    'metamask': 'assets/metamask.png',
    'mongodb': 'assets/mongodb.png',
    'mariadb': 'assets/mariadb.png',
    'deezer': 'assets/deezer.png',
    'postgresql': 'assets/postgresql.png',
    'trust': 'assets/trust.png',
    'basecamp': 'assets/basecamp.png',
    'dropbox': 'assets/dropbox.png',
    'google drive': 'assets/google drive.png',
    'apple': 'assets/apple.png',
    'microsoft onedrive': 'assets/microsoft onedrive.png',
    'oracle virtualbox': 'assets/oracle virtualbox.png',
    'android': 'assets/android.png',
    'ubuntu': 'assets/ubuntu.png',
    'manjaro': 'assets/manjaro.png',
    'archlinux': 'assets/archlinux.png',
    'debian': 'assets/debian.png',
    'freebsd': 'assets/freebsd.png',
    'windows 10': 'assets/windows 10.png',
    'fedora': 'assets/fedora.png',
    'openwrt': 'assets/openwrt.png',
    'centos': 'assets/centos.png',
    'windows 11': 'assets/windows 11.png',
    'openbsd': 'assets/openbsd.png',
    'zorin os': 'assets/zorin os.png',
    'pop!_os': 'assets/pop!_os.png',
    'riot': 'assets/riot.svg',
    'epic': 'assets/epic.png',
    'take': 'assets/take.ai',
    'nintendo': 'assets/nintendo.ai',
    'microsoft': 'assets/microsoft.png',
    'ea': 'assets/ea.png',
    'steam': 'assets/steam.png',
    'bandai': 'assets/bandai.ai',
    'ubisoft': 'assets/ubisoft.png',
    'bethesda': 'assets/bethesda.ai',
  };

  Map<String, String> load() {
    return assets;
  }

  String getAssetPath(String input) {
    if (assets.containsKey(input.toLowerCase())) {
      return assets[input.toLowerCase()]!;
    } else {
      return 'Asset not found!';
    }
  }
}
